# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black:   '#282828'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    magenta: '#b16286'
    cyan:    '#689d6a'
    white:   '#a89984'

  # Bright colors
  bright:
    black:   '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    magenta: '#d3869b'
    cyan:    '#8ec07c'
    white:   '#ebdbb2'


font:
  size: 13

  normal:
    family: 'Cascadia Code PL'
    style: Regular
  bold:
    family: 'Cascadia Code PL'
    style: Bold
  italic:
    family: 'Cascadia Code PL'
    style: Italic
  bold_italic:
    family: 'Cascadia Code PL'
    style: Bold Italic
  offset:
    y: 8
  glyph_offset:
    y: 4

env:
  WINIT_X11_SCALE_FACTOR: "0.85"
