add_newline = false

[character]
symbol = "â€º"
errpr_symbol = "âœ–"
vicmd_symbol = "â€¹"
use_symbol_for_status = true

[cmd_duration]
min_time = 5_000

[git_state]
cherry_pick = "ğŸ’ PICKING"

[nodejs]
disabled = false

[package]
disabled = false

[golang]
disabled = false
