add_newline = false

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ–](bold red)"
vicmd_symbol = "[â¯](bold yellow)"
use_symbol_for_status = true

[cmd_duration]
min_time = 5_000

[git_state]
cherry_pick = "ğŸ’ PICKING"

[nodejs]
disabled = true

[package]
disabled = true

[aws]
disabled = true

[golang]
disabled = false

[battery]
charging_symbol = 'âš¡'
discharging_symbol = 'ğŸ”‹'
