add_newline = false

[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ–](bold red)"
vicmd_symbol = "[â¯](bold yellow)"

[cmd_duration]
min_time = 5_000

[git_state]
cherry_pick = "ğŸ’"
merge = "ğŸ™"
rebase = "ğŸ”„"
revert = "â†ªï¸ "
bisect = "ğŸ”ª"

[git_branch]
symbol = "ğŸŒ± "

[nodejs]
disabled = false

[package]
disabled = true

[aws]
disabled = true

[golang]
disabled = false

[battery]
charging_symbol = 'âš¡'
discharging_symbol = 'ğŸ”‹'

[jobs]
symbol = "ğŸ’¼ "
